const variable = {
  APPWRITE_ENDPOINT: process.env.EXPO_PUBLIC_APPWRITE_ENDPOINT!,
  APPWRITE_PLATFORM: process.env.EXPO_PUBLIC_APPWRITE_PLATFORM!,
  APPWRITE_PROJECT: process.env.EXPO_PUBLIC_APPWRITE_PROJECT!,
  DATABASE_PRIMARY: process.env.EXPO_PUBLIC_DATABASE_PRIMARY!,
  COLLECTION_USER: process.env.EXPO_PUBLIC_COLLECTION_USER!,
  COLLECTION_REQUEST: process.env.EXPO_PUBLIC_COLLECTION_REQUEST!,
  COLLECTION_NOTIFICATION: process.env.EXPO_PUBLIC_COLLECTION_NOTIFICATION!,
};

export const env = variable;
